/*
 * One-off generator: bakes a world land silhouette into the WorldReach map.
 *
 * Reads the public-domain world-atlas land-110m topology, projects every
 * polygon with the SAME equirectangular window as WorldReach.jsx, and writes
 * the result as a plain SVG path string to src/data/worldLand.js — so the app
 * ships real geography with no runtime map library or network fetch.
 *
 * It also patches the standalone preview (scratchpad/reach-preview.html) with
 * the same path, so the artifact preview matches the app.
 *
 * Regenerate (only if the VIEW window below changes):
 *   npm i -D world-atlas topojson-client && node scripts/gen-world.mjs
 */
import { createRequire } from 'module'
import { readFileSync, writeFileSync, existsSync } from 'fs'

const require = createRequire(import.meta.url)
const { feature } = require('topojson-client')
const topo = require('world-atlas/land-110m.json')

// Must match WorldReach.jsx exactly.
const VIEW = { lonMin: -20, lonMax: 125, latMin: -12, latMax: 62, W: 1000 }
const SCALE = VIEW.W / (VIEW.lonMax - VIEW.lonMin)
const H = Math.round((VIEW.latMax - VIEW.latMin) * SCALE)
const px = (lon) => +((lon - VIEW.lonMin) * SCALE).toFixed(1)
const py = (lat) => +((VIEW.latMax - lat) * SCALE).toFixed(1)

// Keep only polygons whose bbox touches an expanded window — drops the Americas,
// southern Africa, Antarctica, etc. so the baked path stays small.
const WIN = { lonMin: -38, lonMax: 143, latMin: -30, latMax: 78 }

const land = feature(topo, topo.objects.land)
const geoms = land.type === 'FeatureCollection' ? land.features.map((f) => f.geometry) : [land.geometry]

function bboxTouches(ring) {
  let mnx = Infinity, mny = Infinity, mxx = -Infinity, mxy = -Infinity
  for (const [lon, lat] of ring) {
    if (lon < mnx) mnx = lon; if (lon > mxx) mxx = lon
    if (lat < mny) mny = lat; if (lat > mxy) mxy = lat
  }
  return !(mxx < WIN.lonMin || mnx > WIN.lonMax || mxy < WIN.latMin || mny > WIN.latMax)
}
function ringPath(ring) {
  let d = ''
  for (let i = 0; i < ring.length; i++) d += (i ? 'L' : 'M') + px(ring[i][0]) + ' ' + py(ring[i][1]) + ' '
  return d + 'Z'
}

const polys = []
for (const g of geoms) {
  if (g.type === 'Polygon') polys.push(g.coordinates)
  else if (g.type === 'MultiPolygon') for (const p of g.coordinates) polys.push(p)
}
let d = '', kept = 0
for (const poly of polys) {
  if (!bboxTouches(poly[0])) continue
  kept++
  for (const ring of poly) d += ringPath(ring)
}

writeFileSync(
  new URL('../src/data/worldLand.js', import.meta.url),
  `// Auto-generated by scripts/gen-world.mjs — do not edit by hand.\n` +
  `// Source: world-atlas land-110m (public domain). Equirectangular projection\n` +
  `// baked to the WorldReach viewBox 0 0 ${VIEW.W} ${H}. Regenerate if VIEW changes:\n` +
  `//   npm i -D world-atlas topojson-client && node scripts/gen-world.mjs\n` +
  `export const WORLD_LAND = ${JSON.stringify(d)}\n`
)

// Patch the standalone artifact preview so it shows the same continents.
const artPath = 'C:/Users/aq/AppData/Local/Temp/claude/C--Users-aq-Desktop-Ruqaa/eea46c35-b133-486e-ac71-e945dc93a2c8/scratchpad/reach-preview.html'
if (existsSync(artPath)) {
  let art = readFileSync(artPath, 'utf8')
  if (!art.includes('.land{')) {
    art = art.replace(
      '.dots circle{ fill:var(--bstrong); opacity:.4; }',
      '.dots circle{ fill:var(--bstrong); opacity:.4; }\n  .land{ fill:var(--panel2); stroke:var(--bstrong); stroke-width:.8; }'
    )
  }
  art = art.replace(/const LAND=".*?";\n  /, '')
  art = art.replace('const VIEW={lonMin', `const LAND=${JSON.stringify(d)};\n  const VIEW={lonMin`)
  if (!art.includes("class=\"land\"")) {
    art = art.replace('let s=grat();', `let s=grat(); s+='<path class="land" d="'+LAND+'"/>';`)
  }
  writeFileSync(artPath, art)
  console.log('patched artifact preview')
}

console.log(`kept ${kept} polygons, path length ${d.length} chars, viewBox 0 0 ${VIEW.W} ${H}`)
